// src/renderer/themes.js
// Theme system with 3 dark + 3 light variants
// Each theme has a complete color palette synced across light/dark

const THEMES = {
  // DARK MODE THEMES
  'dark-teal': {
    mode: 'dark',
    name: 'Deep Teal',
    description: 'Cool, focused energy',
    colors: {
      // Base
      background: '#0B0D17',
      surface: '#131B2E',
      'surface-container-lowest': '#060E20',
      'surface-container-low': '#0F1B2E',
      'surface-container': '#171F33',
      'surface-container-high': '#222A3D',
      'surface-container-highest': '#2D3449',
      'surface-variant': '#3D4947',
      'surface-dim': '#0B1326',
      'surface-bright': '#31394D',
      'surface-tint': '#6BD8CB',

      // Primary (teal)
      primary: '#6BD8CB',
      'primary-container': '#29A195',
      'primary-fixed': '#89F5E7',
      'primary-fixed-dim': '#6BD8CB',
      'on-primary': '#003732',
      'on-primary-container': '#00302B',
      'on-primary-fixed': '#00201D',
      'on-primary-fixed-variant': '#005049',
      'inverse-primary': '#006A61',

      // Secondary (orange)
      secondary: '#FFBA90',
      'secondary-container': '#EC6A06',
      'secondary-fixed': '#FFDBCA',
      'secondary-fixed-dim': '#FFBA90',
      'on-secondary': '#552100',
      'on-secondary-container': '#4A1C00',
      'on-secondary-fixed': '#341100',
      'on-secondary-fixed-variant': '#783200',

      // Tertiary (green)
      tertiary: '#4AE176',
      'tertiary-container': '#00A74B',
      'tertiary-fixed': '#6BFF8F',
      'tertiary-fixed-dim': '#4AE176',
      'on-tertiary': '#003915',
      'on-tertiary-container': '#003111',
      'on-tertiary-fixed': '#002109',
      'on-tertiary-fixed-variant': '#005321',

      // Error (red)
      error: '#FFBA90',
      'error-container': '#93000A',
      'on-error': '#690005',
      'on-error-container': '#FFDAD6',

      // Text
      'on-background': '#DAE2FD',
      'on-surface': '#DAE2FD',
      'on-surface-variant': '#BCC9C6',
      outline: '#879391',
      'outline-variant': '#3D4947',
      'inverse-surface': '#DAE2FD',
      'inverse-on-surface': '#283044',
    },
  },

  'dark-purple': {
    mode: 'dark',
    name: 'Midnight Purple',
    description: 'Deep, creative focus',
    colors: {
      background: '#0B0B1A',
      surface: '#12121F',
      'surface-container-lowest': '#050507',
      'surface-container-low': '#0D0D17',
      'surface-container': '#14141F',
      'surface-container-high': '#1F1F2E',
      'surface-container-highest': '#2A2A3A',
      'surface-variant': '#3D3D4D',
      'surface-dim': '#0B0B1A',
      'surface-bright': '#2E2E3E',
      'surface-tint': '#B59FFF',

      primary: '#B59FFF',
      'primary-container': '#7963C4',
      'primary-fixed': '#D5C4FF',
      'primary-fixed-dim': '#B59FFF',
      'on-primary': '#2D1B52',
      'on-primary-container': '#3D2870',
      'on-primary-fixed': '#20034E',
      'on-primary-fixed-variant': '#4D3B7A',
      'inverse-primary': '#7963C4',

      secondary: '#FFB3D9',
      'secondary-container': '#D946A6',
      'secondary-fixed': '#FFD9EE',
      'secondary-fixed-dim': '#FFB3D9',
      'on-secondary': '#5A1D50',
      'on-secondary-container': '#8B2E7E',
      'on-secondary-fixed': '#42003D',
      'on-secondary-fixed-variant': '#A13A99',

      tertiary: '#7FD8FF',
      'tertiary-container': '#0091D6',
      'tertiary-fixed': '#B1EBFF',
      'tertiary-fixed-dim': '#7FD8FF',
      'on-tertiary': '#00364A',
      'on-tertiary-container': '#004D6B',
      'on-tertiary-fixed': '#001D2E',
      'on-tertiary-fixed-variant': '#005580',

      error: '#FFB3B3',
      'error-container': '#7F0000',
      'on-error': '#5A0000',
      'on-error-container': '#FFD9D6',

      'on-background': '#D9D5DC',
      'on-surface': '#D9D5DC',
      'on-surface-variant': '#C3BCC7',
      outline: '#8F8899',
      'outline-variant': '#49414D',
      'inverse-surface': '#D9D5DC',
      'inverse-on-surface': '#2E2A31',
    },
  },

  'dark-orange': {
    mode: 'dark',
    name: 'Warm Sunset',
    description: 'Energetic, motivating',
    colors: {
      background: '#1A0F00',
      surface: '#2A1810',
      'surface-container-lowest': '#0F0600',
      'surface-container-low': '#1F1410',
      'surface-container': '#281A10',
      'surface-container-high': '#35231A',
      'surface-container-highest': '#402A1F',
      'surface-variant': '#4D3D33',
      'surface-dim': '#1A0F00',
      'surface-bright': '#36241B',
      'surface-tint': '#FFB88A',

      primary: '#FFB88A',
      'primary-container': '#D97D37',
      'primary-fixed': '#FFDCC4',
      'primary-fixed-dim': '#FFB88A',
      'on-primary': '#5D2600',
      'on-primary-container': '#8E4200',
      'on-primary-fixed': '#3D1900',
      'on-primary-fixed-variant': '#A85437',
      'inverse-primary': '#D97D37',

      secondary: '#FFBA8A',
      'secondary-container': '#CC5D1D',
      'secondary-fixed': '#FFDCC4',
      'secondary-fixed-dim': '#FFBA8A',
      'on-secondary': '#602500',
      'on-secondary-container': '#933900',
      'on-secondary-fixed': '#3F1600',
      'on-secondary-fixed-variant': '#B35124',

      tertiary: '#81D8B0',
      'tertiary-container': '#26A877',
      'tertiary-fixed': '#B3F4D6',
      'tertiary-fixed-dim': '#81D8B0',
      'on-tertiary': '#00392C',
      'on-tertiary-container': '#005541',
      'on-tertiary-fixed': '#002817',
      'on-tertiary-fixed-variant': '#1B7A62',

      error: '#FFBAB1',
      'error-container': '#9E0917',
      'on-error': '#690005',
      'on-error-container': '#FFDAD6',

      'on-background': '#E5D5CA',
      'on-surface': '#E5D5CA',
      'on-surface-variant': '#D1C4B9',
      outline: '#9A8E83',
      'outline-variant': '#56483D',
      'inverse-surface': '#E5D5CA',
      'inverse-on-surface': '#35291F',
    },
  },

  // LIGHT MODE THEMES
  'light-teal': {
    mode: 'light',
    name: 'Light Teal',
    description: 'Clean, minimal',
    colors: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F8FAFC',
      'surface-container': '#F1F5F9',
      'surface-container-high': '#E2E8F0',
      'surface-container-highest': '#CBD5E1',
      'surface-variant': '#E2E8F0',
      'surface-dim': '#F1F5F9',
      'surface-bright': '#FFFFFF',
      'surface-tint': '#0D9488',

      primary: '#0D9488',
      'primary-container': '#CCFBF1',
      'primary-fixed': '#99F6E4',
      'primary-fixed-dim': '#2DD4BF',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#115E59',
      'on-primary-fixed': '#00483F',
      'on-primary-fixed-variant': '#134E4A',
      'inverse-primary': '#5EEAD4',

      secondary: '#EA580C',
      'secondary-container': '#FFEDD5',
      'secondary-fixed': '#FED7AA',
      'secondary-fixed-dim': '#FDBA74',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#7C2D12',
      'on-secondary-fixed': '#431407',
      'on-secondary-fixed-variant': '#9A3412',

      tertiary: '#16A34A',
      'tertiary-container': '#DCFCE7',
      'tertiary-fixed': '#86EFAC',
      'tertiary-fixed-dim': '#4ADE80',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#14532D',
      'on-tertiary-fixed': '#0D3817',
      'on-tertiary-fixed-variant': '#166534',

      error: '#DC2626',
      'error-container': '#FEE2E2',
      'on-error': '#FFFFFF',
      'on-error-container': '#991B1B',

      'on-background': '#0F172A',
      'on-surface': '#0F172A',
      'on-surface-variant': '#475569',
      outline: '#94A3B8',
      'outline-variant': '#CBD5E1',
      'inverse-surface': '#1E293B',
      'inverse-on-surface': '#F8FAFC',
    },
  },

  'light-purple': {
    mode: 'light',
    name: 'Light Lavender',
    description: 'Soft, creative',
    colors: {
      background: '#F9F7FC',
      surface: '#FFFFFF',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F9F7FC',
      'surface-container': '#F3F0F8',
      'surface-container-high': '#E8E4F1',
      'surface-container-highest': '#DDD8E8',
      'surface-variant': '#E8E4F1',
      'surface-dim': '#F3F0F8',
      'surface-bright': '#FFFFFF',
      'surface-tint': '#7963C4',

      primary: '#7963C4',
      'primary-container': '#E9DFFF',
      'primary-fixed': '#D5C4FF',
      'primary-fixed-dim': '#B59FFF',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#3D2870',
      'on-primary-fixed': '#2D1B52',
      'on-primary-fixed-variant': '#4D3B7A',
      'inverse-primary': '#D5C4FF',

      secondary: '#D946A6',
      'secondary-container': '#FFD9EE',
      'secondary-fixed': '#FFB3D9',
      'secondary-fixed-dim': '#F472B6',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#8B2E7E',
      'on-secondary-fixed': '#5A1D50',
      'on-secondary-fixed-variant': '#A13A99',

      tertiary: '#0091D6',
      'tertiary-container': '#B1EBFF',
      'tertiary-fixed': '#7FD8FF',
      'tertiary-fixed-dim': '#4FB3FF',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#004D6B',
      'on-tertiary-fixed': '#00364A',
      'on-tertiary-fixed-variant': '#005580',

      error: '#D32F2F',
      'error-container': '#F8D7DA',
      'on-error': '#FFFFFF',
      'on-error-container': '#7D0000',

      'on-background': '#211D26',
      'on-surface': '#211D26',
      'on-surface-variant': '#49414D',
      outline: '#8F8899',
      'outline-variant': '#DDD8E8',
      'inverse-surface': '#35313A',
      'inverse-on-surface': '#F9F7FC',
    },
  },

  'light-orange': {
    mode: 'light',
    name: 'Light Warm',
    description: 'Energetic, friendly',
    colors: {
      background: '#FFFBF7',
      surface: '#FFFFFF',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#FFFBF7',
      'surface-container': '#F8F3ED',
      'surface-container-high': '#EEE5DB',
      'surface-container-highest': '#E3DACD',
      'surface-variant': '#EEE5DB',
      'surface-dim': '#F8F3ED',
      'surface-bright': '#FFFFFF',
      'surface-tint': '#D97D37',

      primary: '#D97D37',
      'primary-container': '#FFDCC4',
      'primary-fixed': '#FFBA8A',
      'primary-fixed-dim': '#FF9D5B',
      'on-primary': '#FFFFFF',
      'on-primary-container': '#8E4200',
      'on-primary-fixed': '#5D2600',
      'on-primary-fixed-variant': '#A85437',
      'inverse-primary': '#FFDCC4',

      secondary: '#CC5D1D',
      'secondary-container': '#FFDCC4',
      'secondary-fixed': '#FFBA8A',
      'secondary-fixed-dim': '#FF9D5B',
      'on-secondary': '#FFFFFF',
      'on-secondary-container': '#933900',
      'on-secondary-fixed': '#602500',
      'on-secondary-fixed-variant': '#B35124',

      tertiary: '#26A877',
      'tertiary-container': '#B3F4D6',
      'tertiary-fixed': '#81D8B0',
      'tertiary-fixed-dim': '#4FBE8F',
      'on-tertiary': '#FFFFFF',
      'on-tertiary-container': '#005541',
      'on-tertiary-fixed': '#002817',
      'on-tertiary-fixed-variant': '#1B7A62',

      error: '#C41C3B',
      'error-container': '#FCE4E6',
      'on-error': '#FFFFFF',
      'on-error-container': '#8B001D',

      'on-background': '#2A1F15',
      'on-surface': '#2A1F15',
      'on-surface-variant': '#56483D',
      outline: '#9A8E83',
      'outline-variant': '#E3DACD',
      'inverse-surface': '#3F3530',
      'inverse-on-surface': '#FFFBF7',
    },
  },
};

export default THEMES;
